services:
  mountebank-server:
    build:
      context: mountebank
    ports:
      - "8882:8882"

  wiremock-server:
    build:
      context: wiremock
    ports:
      - "8883:8080"

  smocker-server:
    build:
      context: smocker
    ports:
      - "8884:8080"
      - "8885:8081"
