services:
  mountebank-server:
    build:
      context: mountebank
    ports:
      - '8882:8882'

  wiremock-server:
    build:
      context: wiremock
    ports:
      - '8883:8080'

  smocker-server:
    build:
      context: smocker
    ports:
      - '8884:8080'
      - '8885:8081'

  prism-server:
    build:
      context: prism
    ports:
      - '8886:4010'

  mockserver-server:
    build:
      context: mockserver
    ports:
      - '8887:1080'

  node-red-server:
    build:
      context: node-red
    ports:
      - '8889:1880'
